version: '3.9'

services:
  database:
    image: mysql:8.0.21
    container_name: database
    ports:
      - ${MYSQLPORT}:${MYSQLPORT}
    environment:
      - MYSQL_DATABASE=Trybesmith
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "database" ]
      timeout: 10s
      retries: 3

  smith_api:
    build: ./
    container_name: smith_api
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:${PORT}" ]
      timeout: 10s
      retries: 5
    ports:
      - ${PORT}:${PORT}
